# Generated by Django 6.0.7 on 2026-07-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('short_description', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='destinations/')),
                ('is_popular', models.BooleanField(default=False, help_text="Show in the Home page 'Popular Destinations' section")),
                ('is_local_tamilnadu', models.BooleanField(default=False, help_text="Tag as part of 'All Local Tamil Nadu Tours'")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
