# Generated by Django 6.0.7 on 2026-07-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('Family Tour', 'Family Tour'), ('College Tour', 'College Tour'), ('Corporate Tour', 'Corporate Tour'), ('Temple Tour', 'Temple Tour'), ('Honeymoon Tour', 'Honeymoon Tour'), ('Weekend Tour', 'Weekend Tour')], max_length=30)),
                ('destination_text', models.CharField(help_text='e.g. Kerala, Ooty & Kodaikanal', max_length=200)),
                ('duration', models.CharField(help_text='e.g. 3 Days / 2 Nights', max_length=50)),
                ('facilities', models.TextField(help_text='One facility per line, e.g. AC Bus, Hotel Stay, Breakfast')),
                ('image', models.ImageField(upload_to='packages/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'tour_type'],
            },
        ),
    ]
